language: python
services: 
  - mongodb
  - rabbitmq
python:
  - "2.6"
  - "2.7"
#  - "3.2"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.4.5    TASK_BACKEND=celery
  - DJANGO_VERSION=1.3.7    TASK_BACKEND=celery
  - DJANGO_VERSION=1.4.5    TASK_BACKEND=ztask
  - DJANGO_VERSION=1.3.7    TASK_BACKEND=ztask

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install -q django-celery
  - pip install -q pyzmq -e git+https://github.com/dmgctrl/django-ztask.git#egg=django_ztask
  - python setup.py -q install
before_script:
#  - mysql -e 'create database myapp_test;'
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
script:
  - python setup.py test
